#!/bin/sh

if [ -z "$PYTHON" ]; then
  PYTHON=$(which python3 2> /dev/null)
fi

if [ -z "$PYTHON" ]; then
  echo 'unable to find python in $PATH'
  exit 1
fi

if [ -z "$@" ]; then
  echo 'Usage:\n\tjwbind <file>'
  exit 1
fi

rm -rf ./java/template/src/*
cp $@ ./java/template/src
(cd ./java/template && make)
cp ./java/template/build/distributions/*.wasm .

# exec "$PYTHON" "pytool/$0.py" "$@"
