#!/bin/sh

if [ -z "$PYTHON" ]; then
  PYTHON=$(which python3 2> /dev/null)
fi

if [ -z "$PYTHON" ]; then
  echo 'unable to find python in $PATH'
  exit 1
fi

if [ -z "$@" ]; then
  echo 'Usage:\n\tjwbind <file>'
  exit 1
fi

JAVA_COM_DIR=java/template
JAVA_SRC_DIR=$JAVA_COM_DIR/src
JAVA_DIST_DIR=$JAVA_COM_DIR/build/distributions
TARGET_NAME=$(basename "$1" ".java")

echo "rootProject.name = '$TARGET_NAME'" > $JAVA_COM_DIR/settings.gradle
rm -rf $JAVA_SRC_DIR/*
cp $@ $JAVA_SRC_DIR
(cd $JAVA_COM_DIR && make)
if [ $? -ne 0 ]; then
  echo 'JWebAssembly compilation failed.'
  exit 1
fi

cp "$JAVA_DIST_DIR/$TARGET_NAME.wasm" .

exec "$PYTHON" "pytool/$0.py" "$TARGET_NAME.wasm"
